// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbzBtw0T-N-chbFyC7tLaESfMG9oItdJU',
    appId: '1:331366928134:web:19f27095e4acf31fcfd887',
    messagingSenderId: '331366928134',
    projectId: 'studence-dev',
    authDomain: 'studence-dev.firebaseapp.com',
    databaseURL: 'https://studence-dev-default-rtdb.firebaseio.com',
    storageBucket: 'studence-dev.appspot.com',
    measurementId: 'G-819JJD2YHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT-DhcViEq8yDjd2-789aA1o8Uw8ioS_I',
    appId: '1:331366928134:android:3eb2cc15c5d1ca9ecfd887',
    messagingSenderId: '331366928134',
    projectId: 'studence-dev',
    databaseURL: 'https://studence-dev-default-rtdb.firebaseio.com',
    storageBucket: 'studence-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDltRrRpG94njEoC8A4ZlNnRvgMJlsIuyM',
    appId: '1:331366928134:ios:6238a99582833cd9cfd887',
    messagingSenderId: '331366928134',
    projectId: 'studence-dev',
    databaseURL: 'https://studence-dev-default-rtdb.firebaseio.com',
    storageBucket: 'studence-dev.appspot.com',
    iosBundleId: 'com.tiwari.studenceMvc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDltRrRpG94njEoC8A4ZlNnRvgMJlsIuyM',
    appId: '1:331366928134:ios:cf345c7e87f98235cfd887',
    messagingSenderId: '331366928134',
    projectId: 'studence-dev',
    databaseURL: 'https://studence-dev-default-rtdb.firebaseio.com',
    storageBucket: 'studence-dev.appspot.com',
    iosBundleId: 'com.example.studenceMvc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbzBtw0T-N-chbFyC7tLaESfMG9oItdJU',
    appId: '1:331366928134:web:0d511c7c82f2b142cfd887',
    messagingSenderId: '331366928134',
    projectId: 'studence-dev',
    authDomain: 'studence-dev.firebaseapp.com',
    databaseURL: 'https://studence-dev-default-rtdb.firebaseio.com',
    storageBucket: 'studence-dev.appspot.com',
    measurementId: 'G-6654X1KHBQ',
  );

}