// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbzBtw0T-N-chbFyC7tLaESfMG9oItdJU',
    appId: '1:331366928134:web:3eedc23c2289d95bcfd887',
    messagingSenderId: '331366928134',
    projectId: 'studence-dev',
    authDomain: 'studence-dev.firebaseapp.com',
    databaseURL: 'https://studence-dev-default-rtdb.firebaseio.com',
    storageBucket: 'studence-dev.appspot.com',
    measurementId: 'G-W7G3LGNQNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT-DhcViEq8yDjd2-789aA1o8Uw8ioS_I',
    appId: '1:331366928134:android:5568c55c6dbae43bcfd887',
    messagingSenderId: '331366928134',
    projectId: 'studence-dev',
    databaseURL: 'https://studence-dev-default-rtdb.firebaseio.com',
    storageBucket: 'studence-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDltRrRpG94njEoC8A4ZlNnRvgMJlsIuyM',
    appId: '1:331366928134:ios:7a80f31e4a32d617cfd887',
    messagingSenderId: '331366928134',
    projectId: 'studence-dev',
    databaseURL: 'https://studence-dev-default-rtdb.firebaseio.com',
    storageBucket: 'studence-dev.appspot.com',
    iosBundleId: 'com.example.studenceMvc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDltRrRpG94njEoC8A4ZlNnRvgMJlsIuyM',
    appId: '1:331366928134:ios:30bbc1c8fa20fa79cfd887',
    messagingSenderId: '331366928134',
    projectId: 'studence-dev',
    databaseURL: 'https://studence-dev-default-rtdb.firebaseio.com',
    storageBucket: 'studence-dev.appspot.com',
    iosBundleId: 'com.example.studenceMvc.RunnerTests',
  );
}
